// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/scan-results/Constellation.tsx": () => import("../components/mockups/scan-results/Constellation.tsx"),
  "./components/mockups/scan-results/Dashboard.tsx": () => import("../components/mockups/scan-results/Dashboard.tsx"),
  "./components/mockups/scan-results/Stories.tsx": () => import("../components/mockups/scan-results/Stories.tsx")
};
